CREATE TABLE players(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  age DECIMAL,
  number DECIMAL,
  position VARCHAR(50),
  photo VARCHAR(255),
  batch_timestamp TIMESTAMP
);

CREATE TABLE fixtures(
  fixture_id SERIAL PRIMARY KEY,
  fixture_referee VARCHAR(255),
  fixture_timezone VARCHAR(50),
  fixture_date TIMESTAMP,
  fixture_timestamp INT,
  fixture_periods_first DECIMAL,
  fixture_periods_second DECIMAL,
  fixture_venue_id DECIMAL,
  fixture_venue_name VARCHAR(255),
  fixture_venue_city VARCHAR(255),
  fixture_status_long VARCHAR(50),
  fixture_status_short VARCHAR(50),
  fixture_status_elapsed DECIMAL,
  league_id INT,
  league_name VARCHAR(255),
  league_country VARCHAR(255),
  league_logo VARCHAR(255),
  league_flag VARCHAR(255),
  league_season INT,
  league_round VARCHAR(255),
  teams_home_id INT,
  teams_home_name VARCHAR(255),
  teams_home_logo VARCHAR(255),
  teams_home_winner BOOLEAN,
  teams_away_id INT,
  teams_away_name VARCHAR(255),
  teams_away_logo VARCHAR(255),
  teams_away_winner BOOLEAN,
  goals_home DECIMAL,
  goals_away DECIMAL,
  score_halftime_home DECIMAL,
  score_halftime_away DECIMAL,
  score_fulltime_home DECIMAL,
  score_fulltime_away DECIMAL,
  score_extratime_home DECIMAL,
  score_extratime_away DECIMAL,
  score_penalty_home DECIMAL,
  score_penalty_away DECIMAL,
  batch_timestamp TIMESTAMP
);

CREATE TABLE fixture_players_statistics(
  team_id INT,
  players_id INT,
  games_minutes DECIMAL,
  games_number INT,
  games_position VARCHAR(50),
  games_rating DECIMAL,
  games_captain BOOLEAN,
  games_substitute BOOLEAN,
  offsides DECIMAL,
  shots_total DECIMAL,
  shots_on DECIMAL,
  goals_total DECIMAL,
  goals_conceded DECIMAL,
  goals_assists DECIMAL,
  goals_saves DECIMAL,
  passes_total DECIMAL,
  passes_key DECIMAL,
  passes_accuracy DECIMAL,
  tackles_total DECIMAL,
  tackles_blocks DECIMAL,
  tackles_interceptions DECIMAL,
  duels_total DECIMAL,
  duels_won DECIMAL,
  dribbles_attempts DECIMAL,
  dribbles_success DECIMAL,
  dribbles_past DECIMAL,
  fouls_drawn DECIMAL,
  fouls_committed DECIMAL,
  cards_yellow INT,
  cards_red INT,
  penalty_won DECIMAL,
  penalty_commited DECIMAL,
  penalty_scored INT,
  penalty_missed INT,
  penalty_saved DECIMAL,
  fixture_id INT,
  batch_timestamp TIMESTAMP,
  FOREIGN KEY(players_id) REFERENCES players(id),
  FOREIGN KEY(fixture_id) REFERENCES fixtures(fixture_id)
  );
